name: photo-deconstruct
channels:
  - conda-forge
  - default
dependencies:
  - matplotlib=3.0.2
  - opencv=3.4.2
  - python=3.7
  - pywavelets=1.0.1
  - pip:
    - click
    - flake8
    - sphinx
    - sphinx_rtd_theme
    - -e .
