name: photo-deconstruct
channels:
  - conda-forge
  - default
dependencies:
  - matplotlib
  - numpy
  - pillow
  - python=3.7
  - pywavelets
  - scikit-image
  - scikit-learn
  - scipy
  - pip:
    - click
    - flake8
    - sphinx
    - sphinx_rtd_theme
    - -e .
