name: photo-deconstruct
channels:
  - default
dependencies:
  - numpy
  - pip
  - pillow
  - python=3.7
  - scipy
  - pip:
    - click
    - flake8
    - matplotlib
    - scikit-image
    - scikit-learn
    - sphinx
    - sphinx_rtd_theme
    - -e .
